server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: api-serie
  data:
    mongodb:
      username: usr-final-mongo
      password: pwd-final-mongo
      database: final-dev-mongo
      port: 27019
      host: localhost
