server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-catalog
  zipkin:
    baseUrl: http://localhost:9411/
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  data:
    mongodb:
      username: usr-final-mongo
      password: pwd-final-mongo
      database: api_catalog_db
      port: 27019
      host: localhost
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info
resilience4j.retry:
  instances:
    retryCatalog:
      maxAttempts: 3
      waitDuration: 10s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
resilience4j.circuitbreaker:
  instances:
    clientCatalog:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 50s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
