server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-serie
  zipkin:
    baseUrl: http://localhost:9411/
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  data:
    mongodb:
      username: usr-final-mongo
      password: pwd-final-mongo
      database: api_serie_db
      port: 27019
      host: localhost
